### ISSUE TITLE
Screenshots

### ISSUE THREAD

**Issue by arouinfar** [phetsims/fractions-mixed-numbers#6]
As pointed out in https://github.com/phetsims/QA/issues/267, this sim needs screenshots for 1.0.

**Comment by amanda-phet** [comment]
@phet-steele Please use the intro screen with the equation visible for the main screenshot.

**Comment by phet-steele** [comment]
Commited. Main followed by alts:

![fractions-mixed-numbers-screenshot](https://user-images.githubusercontent.com/5863899/51766904-05266c00-2099-11e9-90b6-a62168998b06.png)

![fractions-mixed-numbers-screenshot-alt1](https://user-images.githubusercontent.com/5863899/51766907-0788c600-2099-11e9-9499-01b5d132946c.png)

![fractions-mixed-numbers-screenshot-alt2](https://user-images.githubusercontent.com/5863899/51766908-0788c600-2099-11e9-8faa-3c0392323a17.png)

![fractions-mixed-numbers-screenshot-alt3](https://user-images.githubusercontent.com/5863899/51766909-0788c600-2099-11e9-91cb-210d6cf39b37.png)

**Comment by amanda-phet** [comment]
All of these look good to me.
